---
title: "#NationalComingOutDay 2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style>
  div.navbar {
    background-color: black;
    border-bottom: none;
    margin-bottom: 24px;
    box-shadow: 0 4px 0 0 red,
                0 8px 0 0 orange,
                0 12px 0 0 yellow,
                0 16px 0 0 green,
                0 20px 0 0 blue,
                0 24px 0 0 purple;
  }
  #dashboard-container { margin-top: 24px; }
</style>


```{r setup, include=FALSE}
library(flexdashboard)
library(rtweet)
library(tidyverse)
library(ggwordcloud)
library(tidytext)
```

```{r, eval = FALSE}

tweets <- search_tweets(q = "#NationalComingOutDay",
                        n = 10000,
                        include_rts = FALSE)
saveRDS(tweets, "data/tweets.RDS")

tweets2 <- search_tweets(q = "#NationalComingOutDay",
                        n = 10000,
                        max_id = min(tweets$status_id),
                        include_rts = FALSE)
saveRDS(tweets2, "data/tweets2.RDS")
```

```{r}
tweets <- readRDS("data/tweets.RDS") 
tweets2 <- readRDS("data/tweets2.RDS")
```



Column {data-width=650}
-----------------------------------------------------------------------

### Word Cloud

```{r}
omitted <- c(stop_words$word, 0:9, 
             "im", "dont", "amp", "youre", "ive", "didnt")

words <- tweets %>%
  select(text) %>%
  unnest_tokens(output = "word", input = "text", token = "tweets") %>%
  count(word) %>%
  filter(!word %in% omitted) %>%
  slice_max(order_by = n, n = 50)
```

```{r}
ggplot(words, aes(label = word, colour = word, size = n)) +
  geom_text_wordcloud_area()
```


Column {data-width=350}
-----------------------------------------------------------------------

### Top Tweet

```{r}
top_tweet <- tweets %>%
  slice_max(order_by = favorite_count, n = 1)
```


`r top_tweet$text`

by `r top_tweet$screen_name` (`r top_tweet$favorite_count` favorites)

### Trends over time

```{r}
ggplot(tweets, aes(x = created_at)) +
  geom_density()
```

